---
date: "2019-08-21T10:30:38+02:00"
title: Browse data
weight: 10
---


```{r setup, include=FALSE, results='hide', message=FALSE, warning=FALSE}
# hide all code chunks in the output, but show errors
knitr::opts_chunk$set(echo = TRUE,       # hide all code chunks in output
                      error = TRUE,       # show errors if they appear, but don't stop
                      fig.width = 6*1.25, # Figure width
                      fig.height = 6      # Figure height
                     )
# set default NA to - in output, define figure width/height
options(knitr.kable.NA = "-")

# Installing required packages for this template
required_packages <- c("knitr",       # create output docs
                       "dplyr",       # clean/shape data
                       "forcats",     # clean/shape data
                       "stringr",     # clean text
                       "rio",         # read in data
                       "ggplot2",     # create plots and charts
                       "sitrep",      # MSF field epi functions
                       "linelist",    # Functions for cleaning/standardising data
                       "incidence",   # create epicurves
                       "aweek",       # define epi weeks
                       "epitools",    # 2x2 tables and other epi goodness
                       "epitrix",     # epi helpers and tricks
                       "sf",          # encode spatial vector data
                       "ggspatial",
                       "here")   # plot maps

for (pkg in required_packages) {
  # install packages if not already present
  if (!pkg %in% rownames(installed.packages())) {
    install.packages(pkg)
  }
  
  # load packages to this current session 
  library(pkg, character.only = TRUE)
}


# set default text size to 16 for plots
# give classic black/white axes for plots
ggplot2::theme_set(theme_classic(base_size = 18))

# Set the day that defines the beginning of your epiweek.
# you can start the week on any day of the week
# (the ISO standard is to start on Monday) 
aweek::set_week_start("Monday")



date2week("2017-04-20")      #Sys.Date() uses the current date from your computer


reporting_week <- "2017-W16"  # Set the reporting week

# Read in the R object linelist_cleaned that is defined and saved 
# in the AJS_Walkthrough_Cleaning script
linelist_cleaned <- readRDS("data/linelist_aligned.rds")


```



This code chunk can be used to explore your data, but remember to eventually comment these code lines if you do not want these outputs in your final report.



```{r browse_data, warning=FALSE, message=FALSE}
## view the first ten rows of data
head(linelist_cleaned, n = 10)
```


```{r warning=FALSE, message=FALSE}
## view your whole dataset interactivley (in an excel style format)
## Remember that `View` needs to be written with a capital *V*
View(linelist_cleaned)
```


```{r warning=FALSE, message=FALSE}
## overview of variable types and contents
str(linelist_cleaned)
```


```{r warning=FALSE, message=FALSE}
## gives mean, median and max values of variables
## gives counts for categorical variables
## also gives number of NAs
summary(linelist_cleaned)
```


```{r warning=FALSE, message=FALSE}
## view unique values contained in variables 
unique(linelist_cleaned$sex)
```


```{r warning=FALSE, message=FALSE}
## another alternative is with the "summarytools package"
## use the dfSummary function in combination with view
## note that view is not capitalised with this package
# install.packages("summarytools")
# summarytools::view(summarytools::dfSummary(linelist_cleaned))
```


